#!/usr/bin/env bash

environments_dir="~/.i3envs"
source ~/.i3envrc
workspace_name=`i3-msg -t get_workspaces | emuto 'filter ($ => $.focused) | $[0].name | split ": " | [$[1]]' -o raw`
real_env_dir=$(echo $environments_dir | sed "s,~,$HOME,")
env_dir="$real_env_dir/$workspace_name"
command="${@:1}"

echo "Workspace name: $workspace_name"
echo "Environment directory: $env_dir"
echo "Command to run: $command"

(cd "$env_dir"; $($command))
