#!/usr/bin/env bash

environments_dir="~/.i3envs"
source ~/.i3envrc
real_env_dir=$(echo $environments_dir | sed "s,~,$HOME,")

project=`ls $real_env_dir | rofi -dmenu | sed 's/ .*//g'`
workspace_number=`i3-msg -t "get_workspaces" | emuto 'filter ($ => $.focused) | $[0].num'`

if [ -z "$project" ]
then
	echo "Not changing workspace name because no project was selected"
else
	echo "Selected $project"
	workspace_name="$workspace_number: $project"
	env_dir="$real_env_dir/$project"
	echo $workspace_name
	i3-msg "rename workspace to \"$workspace_name\""

	AUTORUN_FILE="$env_dir/.i3-env-autorun"
	if test -f "$AUTORUN_FILE"; then
		i3-env bash $AUTORUN_FILE &
		i3-layout-manager $project &
	else
		i3-env bash ~/.i3-env-autorun &
		i3-layout-manager default &
	fi


fi
cd -
