#!/usr/bin/env bash

environments_dir="~/.i3envs"
source ~/.i3envrc
real_env_dir=$(echo $environments_dir | sed "s,~,$HOME,")

project=`ls $real_env_dir | rofi -dmenu -i | sed 's/ .*//g'`
workspace_number=`i3-msg -t "get_workspaces" | emuto 'filter ($ => $.focused) | $[0].num'`

if [ -z "$project" ]
then
	echo "Not changing workspace name because no project was selected"
else
	echo "Selected $project"
	workspace_name="$workspace_number: $project"
	env_dir="$real_env_dir/$project"
	echo $workspace_name
	found_running_env=`i3-msg -t "get_workspaces" | emuto '~ .name' -o=raw | grep "\:\ $project$" | cut -f1 -d':'`
	echo "found_running_env $found_running_env"
	if [ -z "$found_running_env" ]
	then
		echo "Activating i3-env"
		i3-msg "rename workspace to \"$workspace_name\""

		AUTORUN_FILE="$env_dir/.i3-env-autorun"
		if test -f "$AUTORUN_FILE"; then
			i3-layout-manager $project &
			i3-env bash $AUTORUN_FILE &
			echo "default|$project" > $env_dir/.i3-env-current-mode &
		else
			i3-layout-manager default &
			i3-env bash ~/.i3-env-autorun &
			echo "default|default" > $env_dir/.i3-env-current-mode &
		fi

		# Hack to fix visual glitches
		sleep 1
		i3-msg resize grow width
		i3-msg resize shrink width
	else
		echo "Switching to already active i3-env (workspace $found_running_env)"
		i3-msg "workspace number $found_running_env"
	fi
fi
cd -
